=begin
#API Géo

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.35
=end

require 'spec_helper'
require 'json'

# Unit tests for ApiGeoClient::RgionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RgionsApi' do
  before do
    # run before each test
    @instance = ApiGeoClient::RgionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RgionsApi' do
    it 'should create an instance of RgionsApi' do
      expect(@instance).to be_instance_of(ApiGeoClient::RgionsApi)
    end
  end

  # unit tests for regions_code_departements_get
  # Renvoi les départements d&#x27;une région
  # @param code Code de la région
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @return [Array<Departement>]
  describe 'regions_code_departements_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for regions_code_get
  # Récupérer les informations concernant une région
  # @param code Code de la région
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @return [Region]
  describe 'regions_code_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for regions_get
  # Recherche des régions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :code Code de la région
  # @option opts [String] :nom Nom de la région
  # @option opts [Array<String>] :zone Zone permettant de filtrer à la métropole, aux DROM et aux COM. Défaut à metro,drom sauf pour les communes à metro,drom,com pour conserver le comportement historique.
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @return [Array<Region>]
  describe 'regions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
